//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBookingFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBookingFile()
        {
            this.tbSectorBookings = new HashSet<tbSectorBooking>();
            this.tbPartyGroups = new HashSet<tbPartyGroup>();
        }
    
        public int pkBookingId { get; set; }
        public string PartyName { get; set; }
        public short GuestCount { get; set; }
        public Nullable<short> DefaultRooms { get; set; }
        public System.DateTime DateBookingMade { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int fkUserId { get; set; }
        public Nullable<int> fkLockedByUserId { get; set; }
        public Nullable<int> fkAgentId { get; set; }
        public string fkAgencyCode { get; set; }
        public string fkOrgAgencyCode { get; set; }
        public Nullable<int> fkRate { get; set; }
        public string RulesCheckRequired { get; set; }
        public string RulesViolated { get; set; }
        public string RepeatParty { get; set; }
        public string ExclusiveCamps { get; set; }
        public string SpecialAllocation { get; set; }
        public string Notes { get; set; }
        public string ItineraryNotes { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string TPRef { get; set; }
        public Nullable<int> GuideCount { get; set; }
        public string TransactionId { get; set; }
        public bool Paid { get; set; }
        public Nullable<int> PCMRef { get; set; }
        public Nullable<bool> DontAsk { get; set; }
        public Nullable<double> WishVersion { get; set; }
        public string TPBranchCluster { get; set; }
        public Nullable<bool> IsReverted { get; set; }
        public Nullable<bool> AllowGuestsMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSectorBooking> tbSectorBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPartyGroup> tbPartyGroups { get; set; }
        public virtual tbUser tbUser { get; set; }
        public virtual tbUser tbUser1 { get; set; }
    }
}
