//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbGuest()
        {
            this.tbPartyGroups = new HashSet<tbPartyGroup>();
        }
    
        public int pkGuestId { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Title { get; set; }
        public string fkResidenceCode { get; set; }
        public string fkNationalityCode { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Age { get; set; }
        public string Sharing { get; set; }
        public string Gender { get; set; }
        public Nullable<short> IsGuide { get; set; }
        public Nullable<int> TPGuestId { get; set; }
        public string PassportNumber { get; set; }
        public string PassportName { get; set; }
        public string PassportNationality { get; set; }
        public Nullable<System.DateTime> PassportIssued { get; set; }
        public string PassportPlace { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public Nullable<bool> IsRepeatGuest { get; set; }
        public Nullable<bool> IsPrivateGuide { get; set; }
        public Nullable<int> FK_PrivateGuidID { get; set; }
        public string TPNationality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPartyGroup> tbPartyGroups { get; set; }
    }
}
