//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLodge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLodge()
        {
            this.tset_WishSchedwinLink = new HashSet<tset_WishSchedwinLink>();
            this.tbLodgeBookings = new HashSet<tbLodgeBooking>();
        }
    
        public int pkLodgeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> fkConcessionId { get; set; }
        public Nullable<int> fkLocationId { get; set; }
        public Nullable<int> fkAirstripId { get; set; }
        public Nullable<bool> DisplayInTree { get; set; }
        public Nullable<bool> DisplayInAWISH { get; set; }
        public Nullable<int> ExpiryTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Email { get; set; }
        public int Expiry { get; set; }
        public int fkGroupDivisionId { get; set; }
        public string Ownership { get; set; }
        public string Type { get; set; }
        public int fkRegionId { get; set; }
        public bool IsNew { get; set; }
        public string GPKey { get; set; }
        public string GF_Name { get; set; }
        public string GF_Country { get; set; }
        public string GF_Ownership { get; set; }
        public string GF_Management { get; set; }
        public string GF_Market { get; set; }
        public string GF_Brand { get; set; }
        public string GF_GPDB { get; set; }
        public string GF_TGKPC { get; set; }
        public string GF_Region { get; set; }
        public string GF_Comment { get; set; }
        public Nullable<bool> GF_ReturnData { get; set; }
        public string GF_BrandRate { get; set; }
        public Nullable<short> GF_ReportBeds { get; set; }
        public Nullable<short> GF_TotalBeds { get; set; }
        public Nullable<bool> QV_Marketing { get; set; }
        public string QV_TPCode { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string GF_Price_CCY { get; set; }
        public string GF_Lessor { get; set; }
        public Nullable<bool> ExclusiveUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_WishSchedwinLink> tset_WishSchedwinLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLodgeBooking> tbLodgeBookings { get; set; }
        public virtual tbAirstrip tbAirstrip { get; set; }
    }
}
