//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSectorBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSectorBooking()
        {
            this.tbSectorBookings1 = new HashSet<tbSectorBooking>();
            this.tbSectorBookings11 = new HashSet<tbSectorBooking>();
            this.tbLodgeBookings = new HashSet<tbLodgeBooking>();
            this.tbSefBookings = new HashSet<tbSefBooking>();
            this.tbCharterBookings = new HashSet<tbCharterBooking>();
        }
    
        public int pkSectorBookingId { get; set; }
        public Nullable<int> fkBookingId { get; set; }
        public Nullable<int> fkSafariId { get; set; }
        public string fkSectorClass { get; set; }
        public Nullable<int> fkFromSector { get; set; }
        public Nullable<int> fkToSector { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<int> fkPartyGroupId { get; set; }
        public Nullable<int> fkMealBasisId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<int> fkPrincipalId { get; set; }
        public string fkLocation { get; set; }
        public Nullable<int> fkAirstripId { get; set; }
        public string PrincipalReference { get; set; }
        public Nullable<int> fkAircraftTypeId { get; set; }
        public Nullable<int> fkTransportTypeId { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ExclusiveUse { get; set; }
        public Nullable<System.DateTime> StatusModDate { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> isAgent { get; set; }
        public string RateOption { get; set; }
        public Nullable<bool> AllowGuestsMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSectorBooking> tbSectorBookings1 { get; set; }
        public virtual tbSectorBooking tbSectorBooking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSectorBooking> tbSectorBookings11 { get; set; }
        public virtual tbSectorBooking tbSectorBooking2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLodgeBooking> tbLodgeBookings { get; set; }
        public virtual tbBookingFile tbBookingFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSefBooking> tbSefBookings { get; set; }
        public virtual tbAirstrip tbAirstrip { get; set; }
        public virtual tbPrincipal tbPrincipal { get; set; }
        public virtual tbPartyGroup tbPartyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCharterBooking> tbCharterBookings { get; set; }
        public virtual tbAircraftType tbAircraftType { get; set; }
    }
}
