//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSefFlightSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSefFlightSchedule()
        {
            this.tbSefFlightLegs = new HashSet<tbSefFlightLeg>();
        }
    
        public int pkSefFlightScheduleID { get; set; }
        public int fkSefFlightID { get; set; }
        public System.DateTime WeekStartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSefFlightLeg> tbSefFlightLegs { get; set; }
        public virtual tbSefFlight tbSefFlight { get; set; }
    }
}
