//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSefFlightLeg
    {
        public int pkSefFlightLegID { get; set; }
        public int fkSefFlightScheduleID { get; set; }
        public int fkSefLegID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbSefFlightSchedule tbSefFlightSchedule { get; set; }
        public virtual tbSefLeg tbSefLeg { get; set; }
    }
}
