//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSefFlight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSefFlight()
        {
            this.tbSefBookings = new HashSet<tbSefBooking>();
            this.tbSefFlightSchedules = new HashSet<tbSefFlightSchedule>();
        }
    
        public int pkSefFlightID { get; set; }
        public string Description { get; set; }
        public int fkLocationID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int Expiry { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public string User { get; set; }
        public Nullable<int> fkPrincipalID { get; set; }
    
        public virtual tbPrincipal tbPrincipal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSefBooking> tbSefBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSefFlightSchedule> tbSefFlightSchedules { get; set; }
    }
}
