//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbBookingFiles = new HashSet<tbBookingFile>();
            this.tbBookingFiles1 = new HashSet<tbBookingFile>();
        }
    
        public int pkUserId { get; set; }
        public string PersonCode { get; set; }
        public Nullable<System.Guid> ADirectoryGUID { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public string UserLoggedIn { get; set; }
        public Nullable<int> UsedResSysCount { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBookingFile> tbBookingFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBookingFile> tbBookingFiles1 { get; set; }
    }
}
