//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tset_WishSchedwinLink
    {
        public int pkSchedLinkID { get; set; }
        public Nullable<int> fkLodgeId { get; set; }
        public string CampName { get; set; }
        public string ActualCampName { get; set; }
        public string TPCode { get; set; }
    
        public virtual tbLodge tbLodge { get; set; }
    }
}
