//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFlightLeg
    {
        public System.Guid pkSefFlightLegID { get; set; }
        public int pkSefFlightID { get; set; }
        public string flight_Description { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public Nullable<int> fkSefLegID { get; set; }
        public Nullable<bool> Flight_Active { get; set; }
        public string Leg_Description { get; set; }
        public Nullable<System.DateTime> Leg_Date { get; set; }
    }
}
