//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.WishIntegration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WISHEntities : DbContext
    {
        public WISHEntities()
            : base("name=WISHEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbLodge> tbLodges { get; set; }
        public virtual DbSet<tset_WishSchedwinLink> tset_WishSchedwinLink { get; set; }
        public virtual DbSet<tbSectorBooking> tbSectorBookings { get; set; }
        public virtual DbSet<tbLodgeBooking> tbLodgeBookings { get; set; }
        public virtual DbSet<tbBookingFile> tbBookingFiles { get; set; }
        public virtual DbSet<tbSefFlightSchedule> tbSefFlightSchedules { get; set; }
        public virtual DbSet<tbSefLeg> tbSefLegs { get; set; }
        public virtual DbSet<tbSefBooking> tbSefBookings { get; set; }
        public virtual DbSet<tbSefLegSchedule> tbSefLegSchedules { get; set; }
        public virtual DbSet<tbSefFlightLeg> tbSefFlightLegs { get; set; }
        public virtual DbSet<tbAirstrip> tbAirstrips { get; set; }
        public virtual DbSet<tbPrincipal> tbPrincipals { get; set; }
        public virtual DbSet<tbSefFlight> tbSefFlights { get; set; }
        public virtual DbSet<tbGuest> tbGuests { get; set; }
        public virtual DbSet<tbPartyGroup> tbPartyGroups { get; set; }
        public virtual DbSet<tbCharterBooking> tbCharterBookings { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
        public virtual DbSet<vwLocation> vwLocations { get; set; }
        public virtual DbSet<tbAircraftType> tbAircraftTypes { get; set; }
        public virtual DbSet<vwFlightLeg> vwFlightLegs { get; set; }
    
        public virtual ObjectResult<spSchedwinCharterRetrieval_Result> spSchedwinCharterRetrievalNew(Nullable<int> principalID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> @new)
        {
            var principalIDParameter = principalID.HasValue ?
                new ObjectParameter("PrincipalID", principalID) :
                new ObjectParameter("PrincipalID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var newParameter = @new.HasValue ?
                new ObjectParameter("New", @new) :
                new ObjectParameter("New", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSchedwinCharterRetrieval_Result>("spSchedwinCharterRetrievalNew", principalIDParameter, startDateParameter, endDateParameter, newParameter);
        }
    }
}
