//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nametsol
    {
        public int IDX { get; set; }
        public Nullable<int> IDX_Group { get; set; }
        public string GroupName { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<long> IDX_Passenger { get; set; }
        public Nullable<int> IDX_AP1 { get; set; }
        public Nullable<int> IDX_AP12 { get; set; }
        public Nullable<int> IDX_ResLeg1 { get; set; }
        public Nullable<System.DateTime> Leg1Date { get; set; }
        public string Leg1AP1 { get; set; }
        public string Leg1AP2 { get; set; }
        public Nullable<int> IDX_AP2 { get; set; }
        public Nullable<int> IDX_AP22 { get; set; }
        public Nullable<int> IDX_ResLeg2 { get; set; }
        public Nullable<System.DateTime> Leg2Date { get; set; }
        public string Leg2AP1 { get; set; }
        public string Leg2AP2 { get; set; }
        public Nullable<int> IDX_AP3 { get; set; }
        public Nullable<int> IDX_AP32 { get; set; }
        public Nullable<int> IDX_ResLeg3 { get; set; }
        public Nullable<System.DateTime> Leg3Date { get; set; }
        public string Leg3AP1 { get; set; }
        public string Leg3AP2 { get; set; }
        public Nullable<int> IDX_AP4 { get; set; }
        public Nullable<int> IDX_AP42 { get; set; }
        public Nullable<int> IDX_ResLeg4 { get; set; }
        public Nullable<System.DateTime> Leg4Date { get; set; }
        public string Leg4AP1 { get; set; }
        public string Leg4AP2 { get; set; }
        public Nullable<int> IDX_AP5 { get; set; }
        public Nullable<int> IDX_AP52 { get; set; }
        public Nullable<int> IDX_ResLeg5 { get; set; }
        public Nullable<System.DateTime> Leg5Date { get; set; }
        public string Leg5AP1 { get; set; }
        public string Leg5AP2 { get; set; }
        public Nullable<int> IDX_AP6 { get; set; }
        public Nullable<int> IDX_AP62 { get; set; }
        public Nullable<int> IDX_ResLeg6 { get; set; }
        public Nullable<System.DateTime> Leg6Date { get; set; }
        public string Leg6AP1 { get; set; }
        public string Leg6AP2 { get; set; }
        public Nullable<int> IDX_AP7 { get; set; }
        public Nullable<int> IDX_AP72 { get; set; }
        public Nullable<int> IDX_ResLeg7 { get; set; }
        public Nullable<System.DateTime> Leg7Date { get; set; }
        public string Leg7AP1 { get; set; }
        public string Leg7AP2 { get; set; }
        public string Pilot { get; set; }
        public string Aircraft { get; set; }
        public string Number { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public string IssuedBy { get; set; }
    }
}
