//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchedwinRegionalEntities : DbContext
    {
        public SchedwinRegionalEntities()
            : base("name=SchedwinRegionalEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Techlog> t_Techlog { get; set; }
        public virtual DbSet<t_Techlog_Fuel> t_Techlog_Fuel { get; set; }
        public virtual DbSet<T_Techlog_Services> T_Techlog_Services { get; set; }
        public virtual DbSet<t_TechlogFlightTime> t_TechlogFlightTime { get; set; }
        public virtual DbSet<timg_Documents> timg_Documents { get; set; }
        public virtual DbSet<timg_Pictures> timg_Pictures { get; set; }
        public virtual DbSet<tlst_PaxType> tlst_PaxType { get; set; }
        public virtual DbSet<tlst_PersonnelType> tlst_PersonnelType { get; set; }
        public virtual DbSet<tlst_PilotTypes> tlst_PilotTypes { get; set; }
        public virtual DbSet<tlst_ResStatus> tlst_ResStatus { get; set; }
        public virtual DbSet<tlst_ResType> tlst_ResType { get; set; }
        public virtual DbSet<tsch_InUse> tsch_InUse { get; set; }
        public virtual DbSet<tsch_Legs> tsch_Legs { get; set; }
        public virtual DbSet<tsch_Loadsheet> tsch_Loadsheet { get; set; }
        public virtual DbSet<tsch_Passengers> tsch_Passengers { get; set; }
        public virtual DbSet<tsch_PilotRoster> tsch_PilotRoster { get; set; }
        public virtual DbSet<tsch_ReservationHeader> tsch_ReservationHeader { get; set; }
        public virtual DbSet<tsch_ReservationLegBudget> tsch_ReservationLegBudget { get; set; }
        public virtual DbSet<tsch_ReservationLegs> tsch_ReservationLegs { get; set; }
        public virtual DbSet<tsch_SplitReservations> tsch_SplitReservations { get; set; }
        public virtual DbSet<tsch_TrackingTime> tsch_TrackingTime { get; set; }
        public virtual DbSet<tsch_WeightBalance> tsch_WeightBalance { get; set; }
        public virtual DbSet<tset_ACDetails> tset_ACDetails { get; set; }
        public virtual DbSet<tset_ACEnvelope> tset_ACEnvelope { get; set; }
        public virtual DbSet<tset_ACPaxStation> tset_ACPaxStation { get; set; }
        public virtual DbSet<tset_ACTypes> tset_ACTypes { get; set; }
        public virtual DbSet<tset_AirportFeesNew> tset_AirportFeesNew { get; set; }
        public virtual DbSet<tset_Airports> tset_Airports { get; set; }
        public virtual DbSet<tset_Distance> tset_Distance { get; set; }
        public virtual DbSet<tset_Lodges> tset_Lodges { get; set; }
        public virtual DbSet<tset_Personnel> tset_Personnel { get; set; }
        public virtual DbSet<tset_Pictures> tset_Pictures { get; set; }
        public virtual DbSet<tsch_LegsRes> tsch_LegsRes { get; set; }
        public virtual DbSet<tsch_WISHIntegrationHeader> tsch_WISHIntegrationHeader { get; set; }
        public virtual DbSet<tsch_WishIntegrationLeg> tsch_WishIntegrationLeg { get; set; }
        public virtual DbSet<tset_ACDetailTypeStations> tset_ACDetailTypeStations { get; set; }
        public virtual DbSet<tset_ACTypeLoadingArrangement> tset_ACTypeLoadingArrangement { get; set; }
        public virtual DbSet<tset_ACTypes_Station> tset_ACTypes_Station { get; set; }
        public virtual DbSet<tset_Airportsfees> tset_Airportsfees { get; set; }
        public virtual DbSet<tset_AllowableDutyHours> tset_AllowableDutyHours { get; set; }
        public virtual DbSet<tset_AllowbleHours> tset_AllowbleHours { get; set; }
        public virtual DbSet<tset_Limitations> tset_Limitations { get; set; }
        public virtual DbSet<tlst_StationType> tlst_StationType { get; set; }
        public virtual DbSet<tset_ACWeightStation> tset_ACWeightStation { get; set; }
        public virtual DbSet<tset_airportFeeType> tset_airportFeeType { get; set; }
        public virtual DbSet<tset_Companies> tset_Companies { get; set; }
        public virtual DbSet<tset_Countries> tset_Countries { get; set; }
        public virtual DbSet<tset_Flights_Camps> tset_Flights_Camps { get; set; }
        public virtual DbSet<tset_Fuel> tset_Fuel { get; set; }
        public virtual DbSet<tset_OperatorPriceLists> tset_OperatorPriceLists { get; set; }
        public virtual DbSet<tset_OperatorSeatRate> tset_OperatorSeatRate { get; set; }
        public virtual DbSet<tset_PassengerTicketHistory> tset_PassengerTicketHistory { get; set; }
        public virtual DbSet<tset_PilotsDetails> tset_PilotsDetails { get; set; }
        public virtual DbSet<tset_RosterDutyTypes> tset_RosterDutyTypes { get; set; }
        public virtual DbSet<tset_TP_BranchCode_DB> tset_TP_BranchCode_DB { get; set; }
        public virtual DbSet<tset_TP_Region_DB> tset_TP_Region_DB { get; set; }
        public virtual DbSet<tset_TP_Routing_Codes> tset_TP_Routing_Codes { get; set; }
        public virtual DbSet<tset_FuelTypes> tset_FuelTypes { get; set; }
        public virtual DbSet<tset_ModulePermissions> tset_ModulePermissions { get; set; }
        public virtual DbSet<vl_CompanyOperatorsAgents> vl_CompanyOperatorsAgents { get; set; }
        public virtual DbSet<tGP_CurrencyInformation> tGP_CurrencyInformation { get; set; }
        public virtual DbSet<tlst_CompanyType> tlst_CompanyType { get; set; }
        public virtual DbSet<tset_StandardPassengerWeights> tset_StandardPassengerWeights { get; set; }
        public virtual DbSet<tset_GPExportInfo> tset_GPExportInfo { get; set; }
        public virtual DbSet<vw_WishGuestsPartyGroup> vw_WishGuestsPartyGroup { get; set; }
        public virtual DbSet<vl_LastServiceCaptureDate> vl_LastServiceCaptureDate { get; set; }
        public virtual DbSet<tGP_ConnectInformation> tGP_ConnectInformation { get; set; }
        public virtual DbSet<tsch_AC_Pilot> tsch_AC_Pilot { get; set; }
        public virtual DbSet<tsch_LegWeightBalances> tsch_LegWeightBalances { get; set; }
        public virtual DbSet<tlst_Currency> tlst_Currency { get; set; }
    
        public virtual ObjectResult<sl_WISHLegBudgets_Result> sl_WISHLegBudgets(Nullable<int> iDX_RH)
        {
            var iDX_RHParameter = iDX_RH.HasValue ?
                new ObjectParameter("IDX_RH", iDX_RH) :
                new ObjectParameter("IDX_RH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sl_WISHLegBudgets_Result>("sl_WISHLegBudgets", iDX_RHParameter);
        }
    
        public virtual ObjectResult<sl_WISHLegs_Result> sl_WISHLegs(Nullable<int> iDX_RH)
        {
            var iDX_RHParameter = iDX_RH.HasValue ?
                new ObjectParameter("IDX_RH", iDX_RH) :
                new ObjectParameter("IDX_RH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sl_WISHLegs_Result>("sl_WISHLegs", iDX_RHParameter);
        }
    
        public virtual int sd_WISHReservationDelete(Nullable<int> iDX_RH)
        {
            var iDX_RHParameter = iDX_RH.HasValue ?
                new ObjectParameter("IDX_RH", iDX_RH) :
                new ObjectParameter("IDX_RH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sd_WISHReservationDelete", iDX_RHParameter);
        }
    
        public virtual ObjectResult<sl_AirportClosestFuel_Result> sl_AirportClosestFuel(Nullable<System.DateTime> flightDate)
        {
            var flightDateParameter = flightDate.HasValue ?
                new ObjectParameter("FlightDate", flightDate) :
                new ObjectParameter("FlightDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sl_AirportClosestFuel_Result>("sl_AirportClosestFuel", flightDateParameter);
        }
    
        public virtual ObjectResult<sl_GPInvoicing_Result> sl_GPInvoicing(Nullable<System.DateTime> flightDate)
        {
            var flightDateParameter = flightDate.HasValue ?
                new ObjectParameter("FlightDate", flightDate) :
                new ObjectParameter("FlightDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sl_GPInvoicing_Result>("sl_GPInvoicing", flightDateParameter);
        }
    
        [DbFunction("SchedwinRegionalEntities", "fg_AircraftsLastPosition")]
        public virtual IQueryable<fg_AircraftsLastPosition_Result> fg_AircraftsLastPosition(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fg_AircraftsLastPosition_Result>("[SchedwinRegionalEntities].[fg_AircraftsLastPosition](@Date)", dateParameter);
        }
    
        public virtual ObjectResult<sl_ScheduleReservations_Result1> sl_ScheduleReservations(Nullable<System.DateTime> flightDate)
        {
            var flightDateParameter = flightDate.HasValue ?
                new ObjectParameter("FlightDate", flightDate) :
                new ObjectParameter("FlightDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sl_ScheduleReservations_Result1>("sl_ScheduleReservations", flightDateParameter);
        }
    }
}
