//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    
    public partial class sl_ScheduleReservations_Result1
    {
        public string FromAP { get; set; }
        public Nullable<int> IDX_FromAP { get; set; }
        public string ToAP { get; set; }
        public Nullable<int> IDX_ToAP { get; set; }
        public Nullable<int> NumPax { get; set; }
        public string ReservationName { get; set; }
        public string ExField { get; set; }
        public string ForField { get; set; }
        public string Operator { get; set; }
        public Nullable<int> IDX_RH { get; set; }
        public Nullable<int> IDX_RL { get; set; }
        public Nullable<int> PassengerWeight { get; set; }
        public Nullable<int> LuggageWeight { get; set; }
        public Nullable<bool> SoleUse { get; set; }
        public string AcType { get; set; }
        public int IDX_ACType { get; set; }
        public Nullable<System.DateTime> EarlyEx { get; set; }
        public Nullable<System.DateTime> LateEx { get; set; }
        public Nullable<System.DateTime> EarlyFor { get; set; }
        public Nullable<System.DateTime> LateFor { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string ResType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> GameFlight { get; set; }
    }
}
