//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Techlog_Services
    {
        public int IDX { get; set; }
        public Nullable<int> TechlogID { get; set; }
        public System.DateTime Date { get; set; }
        public int IDX_Setup_Aircraft_Details { get; set; }
        public Nullable<double> TTSinceCOfA { get; set; }
        public Nullable<double> TTAirframe { get; set; }
        public Nullable<double> TTEngineOH { get; set; }
        public Nullable<double> TTEngine { get; set; }
        public Nullable<double> TTPropOH { get; set; }
        public Nullable<double> TTProp { get; set; }
        public Nullable<double> TTSinceCOfM { get; set; }
        public string CoCode { get; set; }
        public Nullable<double> TTEngine2OH { get; set; }
        public Nullable<double> TTEngine2 { get; set; }
        public Nullable<double> TTProp2OH { get; set; }
        public Nullable<double> TTProp2 { get; set; }
        public bool DidTTSinceCofA { get; set; }
        public bool DIDTTSinceCofM { get; set; }
        public bool DidTTEngineOH { get; set; }
        public bool DidTTEngine { get; set; }
        public bool DidTTPropOH { get; set; }
        public bool DidTTProp { get; set; }
        public bool DidTTEngine2OH { get; set; }
        public bool DidTTEngine2 { get; set; }
        public bool DidTTProp2OH { get; set; }
        public bool DidTTProp2 { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    }
}
