//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Techlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Techlog()
        {
            this.t_Techlog_Fuel = new HashSet<t_Techlog_Fuel>();
        }
    
        public int IDX { get; set; }
        public int TechlogID { get; set; }
        public int IDX_Pilots { get; set; }
        public int IDX_AC_Details { get; set; }
        public System.DateTime TechlogDate { get; set; }
        public double TachEnd { get; set; }
        public string ActualRoute { get; set; }
        public string ScheduledRoute { get; set; }
        public bool DifferentRoute { get; set; }
        public int ActualDistance { get; set; }
        public int ScheduledDistance { get; set; }
        public double ActualGameflightTime { get; set; }
        public double ScheduledGameflightTime { get; set; }
        public double Speed { get; set; }
        public double FlightTime { get; set; }
        public short Landings { get; set; }
        public string MaintenanceDetails { get; set; }
        public Nullable<double> MaintenanceCost { get; set; }
        public string CoCode { get; set; }
        public Nullable<int> NonrevType { get; set; }
        public Nullable<int> Nonrevenue { get; set; }
        public Nullable<int> NonrevDetails { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Cycles { get; set; }
        public int Starts { get; set; }
        public Nullable<int> IDX_Pilots2 { get; set; }
        public double TachStart { get; set; }
        public double PilotFlightTime { get; set; }
        public System.DateTime DutyTimeStart { get; set; }
        public System.DateTime DutyTimeEnd { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual tset_ACDetails tset_ACDetails { get; set; }
        public virtual tset_Personnel tset_Personnel { get; set; }
        public virtual tset_Personnel tset_Personnel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Techlog_Fuel> t_Techlog_Fuel { get; set; }
    }
}
