//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Techlog_Fuel
    {
        public long IDX { get; set; }
        public int TechlogID { get; set; }
        public double FuelCost { get; set; }
        public int FuelQty { get; set; }
        public double OilCost { get; set; }
        public int OilQty { get; set; }
        public string Receipt { get; set; }
        public string CoCode { get; set; }
        public int IDX_Techlog { get; set; }
        public Nullable<int> IDX_Airports { get; set; }
        public Nullable<int> IDX_Currency { get; set; }
        public int IDX_AC_Details { get; set; }
        public int IDX_AirportDest { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual t_Techlog t_Techlog { get; set; }
        public virtual tset_Airports tset_Airports { get; set; }
        public virtual tset_Airports tset_Airports1 { get; set; }
        public virtual tlst_Currency tlst_Currency { get; set; }
    }
}
