//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAircraft
    {
        public int pkAircraftID { get; set; }
        public Nullable<int> fkAircraftTypeID { get; set; }
        public int fkCountryID { get; set; }
        public string Registration { get; set; }
        public double EmptyMass { get; set; }
        public double EmptyArm { get; set; }
        public Nullable<int> fkOwnerID { get; set; }
        public string Colours { get; set; }
        public string Equipment { get; set; }
        public float BuyingRate { get; set; }
        public float SellingRate { get; set; }
        public string InvoiceCode { get; set; }
        public int AvgSpeed { get; set; }
        public byte OwnAircraft { get; set; }
        public byte Active { get; set; }
        public Nullable<int> fkUnderwriterID { get; set; }
        public string Liability { get; set; }
        public System.DateTime InsuranceExp { get; set; }
        public Nullable<int> Demurrage { get; set; }
        public Nullable<float> ShortCycleFee { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<System.DateTime> YOM { get; set; }
        public Nullable<double> TTA { get; set; }
        public Nullable<System.DateTime> DTT { get; set; }
        public Nullable<int> Reserve_Fuel { get; set; }
        public string NavComm1 { get; set; }
        public string NavComm2 { get; set; }
        public string AutoPilot { get; set; }
        public string Wx { get; set; }
        public string GPS { get; set; }
        public string TCAS { get; set; }
        public string EGPWS { get; set; }
        public string HF { get; set; }
        public string FM { get; set; }
        public string MFD { get; set; }
        public string Transponder { get; set; }
        public int TotalFuelWT { get; set; }
        public string ProfitCenter { get; set; }
    }
}
