//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAircraftType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAircraftType()
        {
            this.tbAirportFeeTypes = new HashSet<tbAirportFeeType>();
            this.tbReservationLegBudgets = new HashSet<tbReservationLegBudget>();
        }
    
        public int pkAircraftTypeID { get; set; }
        public string ACType { get; set; }
        public int MaxGrossWeight { get; set; }
        public short BlockSpeed { get; set; }
        public short NumberOfPassengers { get; set; }
        public short AdditionalTurnaroundTime { get; set; }
        public float RangeKm { get; set; }
        public float RangeHours { get; set; }
        public int FuelType { get; set; }
        public short FuelFlow { get; set; }
        public Nullable<double> FuelArm { get; set; }
        public byte TwinEngine { get; set; }
        public string ShortDescription { get; set; }
        public short Demurrage { get; set; }
        public short MaxStops { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAirportFeeType> tbAirportFeeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReservationLegBudget> tbReservationLegBudgets { get; set; }
    }
}
