//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAirportFee
    {
        public int pkAirportFeeID { get; set; }
        public int fkAirportFeeType { get; set; }
        public int fkAirstripID { get; set; }
        public double Value { get; set; }
        public int fkCurrencyID { get; set; }
    
        public virtual tbAirportFeeType tbAirportFeeType { get; set; }
        public virtual tbAirstrip tbAirstrip { get; set; }
        public virtual tbCurrency tbCurrency { get; set; }
    }
}
