//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDBRegionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDBRegionInfo()
        {
            this.tbUserRoles = new HashSet<tbUserRole>();
        }
    
        public int pkDBRegionInfo { get; set; }
        public string Region { get; set; }
        public string Server { get; set; }
        public string Database { get; set; }
        public Nullable<bool> Display { get; set; }
        public Nullable<int> DefaultCountryID { get; set; }
        public Nullable<int> DefaultCurrencyID { get; set; }
        public Nullable<int> GPCompanyID { get; set; }
        public Nullable<int> APIServiceID { get; set; }
        public Nullable<int> DefaultOperatorID { get; set; }
        public string Location { get; set; }
        public Nullable<bool> WishEnabled { get; set; }
        public Nullable<bool> IsTrackingEnabled { get; set; }
        public string WishCode { get; set; }
        public Nullable<bool> WishStatusRetrieve { get; set; }
        public string ConnectionString { get; set; }
        public Nullable<int> PrincipalID { get; set; }
        public Nullable<int> SoleUsePrincipalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserRole> tbUserRoles { get; set; }
    }
}
