//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFlight
    {
        public int pkFlightID { get; set; }
        public int fkCountryID { get; set; }
        public string Description { get; set; }
        public Nullable<int> fkAirstripID { get; set; }
        public string tmpAirstripIATA { get; set; }
        public System.DateTime TimeIn { get; set; }
        public System.DateTime TimeOut { get; set; }
        public bool Active { get; set; }
    
        public virtual tbAirstrip tbAirstrip { get; set; }
        public virtual tbCountry tbCountry { get; set; }
    }
}
