//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbModulePermission
    {
        public int pkModulePermissionID { get; set; }
        public int fkUserID { get; set; }
        public string Module_Name { get; set; }
        public bool Can_Modify { get; set; }
        public bool Can_View { get; set; }
    
        public virtual tbUser tbUser { get; set; }
    }
}
