//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOperator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOperator()
        {
            this.tbOperatorAgents = new HashSet<tbOperatorAgent>();
            this.tbReservationHeaders = new HashSet<tbReservationHeader>();
        }
    
        public int pkOperatorID { get; set; }
        public int fkCountryID { get; set; }
        public string Name { get; set; }
        public string Phone_No { get; set; }
        public string Postal_Address { get; set; }
        public string Physical_Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> fkBaseAPID { get; set; }
        public string GP_ID { get; set; }
        public bool Active { get; set; }
    
        public virtual tbCountry tbCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOperatorAgent> tbOperatorAgents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReservationHeader> tbReservationHeaders { get; set; }
    }
}
