//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPassenger
    {
        public int pkPassengerID { get; set; }
        public int fkReservationHeaderID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<bool> TicketPrinted { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Luggageweight { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Sex { get; set; }
        public Nullable<int> fkPassengerTypeID { get; set; }
        public Nullable<int> WISHGuestID { get; set; }
        public string Passport { get; set; }
        public string Nationality { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tbReservationHeader tbReservationHeader { get; set; }
        public virtual tbPassengerType tbPassengerType { get; set; }
    }
}
