//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPilot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPilot()
        {
            this.tbPilotRosters = new HashSet<tbPilotRoster>();
        }
    
        public int pkPilotID { get; set; }
        public Nullable<int> fkUserID { get; set; }
        public string Nationality { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime PassportExpiryDate { get; set; }
        public string PilotsAddress { get; set; }
        public string PilotsTelephone { get; set; }
        public string PilotsFax { get; set; }
        public string PilotsLicenseNumber { get; set; }
        public System.DateTime PilotsLicenseExpiryDate { get; set; }
        public bool CanRoster { get; set; }
        public string InstrumentRating { get; set; }
        public Nullable<System.DateTime> InstrumentRatingExpiryDate { get; set; }
        public string InstructorRating { get; set; }
        public Nullable<System.DateTime> InstructorRatingExpiryDate { get; set; }
        public string ResidencePermitNumber { get; set; }
        public System.DateTime ResidencePermitExpiryDate { get; set; }
        public string WorkPermitNumber { get; set; }
        public System.DateTime WorkPermitExpiryDate { get; set; }
        public string ContactName { get; set; }
        public string ContactCompany { get; set; }
        public string ContactAddress { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactFax { get; set; }
        public System.DateTime StartingDate { get; set; }
        public double StartingFlyingHours { get; set; }
        public bool Active { get; set; }
        public System.DateTime CofT { get; set; }
        public System.DateTime RouteCheck { get; set; }
        public System.DateTime Medical { get; set; }
        public Nullable<bool> CRM { get; set; }
        public Nullable<System.DateTime> CRMDate { get; set; }
        public Nullable<bool> DangerousGoods { get; set; }
        public Nullable<System.DateTime> DangerousGoodsDate { get; set; }
        public Nullable<System.DateTime> CofT206 { get; set; }
        public Nullable<System.DateTime> CofT208 { get; set; }
        public Nullable<System.DateTime> CofTGA8 { get; set; }
        public short PilotWeight { get; set; }
        public Nullable<System.DateTime> CofTC210 { get; set; }
        public Nullable<System.DateTime> CofTPC12 { get; set; }
        public Nullable<System.DateTime> CofTC402 { get; set; }
        public Nullable<System.DateTime> CofTC510 { get; set; }
        public bool AllTagsSigned { get; set; }
        public Nullable<System.DateTime> CofTC310 { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public byte[] PilotsLicenceImage { get; set; }
        public Nullable<bool> SEPT { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> OPC { get; set; }
        public Nullable<System.DateTime> SEPTDate { get; set; }
        public Nullable<System.DateTime> SMSDate { get; set; }
        public Nullable<System.DateTime> OPCDate { get; set; }
        public int fkCountryID { get; set; }
    
        public virtual tbCountry tbCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPilotRoster> tbPilotRosters { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
