//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPilotRoster
    {
        public int pkPilotRosterID { get; set; }
        public System.DateTime Date { get; set; }
        public int fkPilotID { get; set; }
        public int fkRosterDutyTypeID { get; set; }
    
        public virtual tbRosterDutyType tbRosterDutyType { get; set; }
        public virtual tbPilot tbPilot { get; set; }
    }
}
