//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationLeg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReservationLeg()
        {
            this.tbReservationLegBudgets = new HashSet<tbReservationLegBudget>();
            this.tbWishIntegrationLegs = new HashSet<tbWishIntegrationLeg>();
        }
    
        public int pkReservationLegID { get; set; }
        public int fkReservationHeaderID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int fkFromAirstripID { get; set; }
        public string ExField { get; set; }
        public int fkToAirstripID { get; set; }
        public string ForField { get; set; }
        public Nullable<System.DateTime> EarliestEx { get; set; }
        public Nullable<System.DateTime> LatestEx { get; set; }
        public Nullable<System.DateTime> EarliestFor { get; set; }
        public Nullable<System.DateTime> LatestFor { get; set; }
        public double Budget { get; set; }
        public short DirectDistance { get; set; }
        public double GameflightTime { get; set; }
        public string Notes { get; set; }
        public int fkUserID { get; set; }
        public int fkOperatorID { get; set; }
        public Nullable<bool> TicketPrinted { get; set; }
        public Nullable<int> fkScheduleACPilotID { get; set; }
        public Nullable<int> fkACTypeID { get; set; }
        public Nullable<bool> SoleUse { get; set; }
        public Nullable<long> WISHIDLegs { get; set; }
        public Nullable<int> fkPriceListID { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string Voucher { get; set; }
        public string INV_Number { get; set; }
        public string RateType { get; set; }
        public Nullable<bool> FOC { get; set; }
        public string Currency { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public Nullable<int> fkLegParentID { get; set; }
        public Nullable<int> SEQNo { get; set; }
    
        public virtual tbAirstrip tbAirstrip { get; set; }
        public virtual tbAirstrip tbAirstrip1 { get; set; }
        public virtual tbReservationHeader tbReservationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReservationLegBudget> tbReservationLegBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbWishIntegrationLeg> tbWishIntegrationLegs { get; set; }
    }
}
