//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReservationHeader()
        {
            this.tbPassengers = new HashSet<tbPassenger>();
            this.tbReservationLegs = new HashSet<tbReservationLeg>();
            this.tbWISHIntegrationHeaders = new HashSet<tbWISHIntegrationHeader>();
        }
    
        public int pkReservationHeaderID { get; set; }
        public string Reservationname { get; set; }
        public System.DateTime DateCaptured { get; set; }
        public int Numpax { get; set; }
        public int fkOperatorID { get; set; }
        public Nullable<int> fkOperatorAgentID { get; set; }
        public int fkUserID { get; set; }
        public int fkResStatusID { get; set; }
        public bool Active { get; set; }
        public bool TicketPrinted { get; set; }
        public bool TicketRequired { get; set; }
        public int fkResTypeID { get; set; }
        public Nullable<int> fkResClassID { get; set; }
        public Nullable<int> OLD_IDX { get; set; }
        public string Notes { get; set; }
        public Nullable<int> WISHID { get; set; }
        public string Voucher { get; set; }
        public string CURNCYID { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public int fkCountryID { get; set; }
    
        public virtual tbCountry tbCountry { get; set; }
        public virtual tbOperator tbOperator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPassenger> tbPassengers { get; set; }
        public virtual tbReservationStatus tbReservationStatu { get; set; }
        public virtual tbReservationType tbReservationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReservationLeg> tbReservationLegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbWISHIntegrationHeader> tbWISHIntegrationHeaders { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
