//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationLegBudget
    {
        public int pkReservationLegBudgetID { get; set; }
        public int fkReservationLegID { get; set; }
        public int fkFromAPID { get; set; }
        public int fkToAPID { get; set; }
        public int fkACTypeID { get; set; }
        public string Currency { get; set; }
        public string RateType { get; set; }
        public int fkPriceList { get; set; }
        public double Budget { get; set; }
        public Nullable<double> Tax { get; set; }
        public bool FOC { get; set; }
        public double Qty { get; set; }
        public double Rate { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tbAircraftType tbAircraftType { get; set; }
        public virtual tbAirstrip tbAirstrip { get; set; }
        public virtual tbAirstrip tbAirstrip1 { get; set; }
        public virtual tbReservationLeg tbReservationLeg { get; set; }
    }
}
