//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRoleScreenAccess
    {
        public int pkRoleScreenAccess { get; set; }
        public int fkRoleID { get; set; }
        public bool Access { get; set; }
        public bool View { get; set; }
        public bool Add { get; set; }
        public bool Edit { get; set; }
        public string ScreenName { get; set; }
    
        public virtual tbRole tbRole { get; set; }
    }
}
