//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStandardPaxWeight
    {
        public int pkStandardPaxWeightID { get; set; }
        public int MinRange { get; set; }
        public int MaxRange { get; set; }
        public int Male { get; set; }
        public int Female { get; set; }
        public int Luggage { get; set; }
        public int fkCountryID { get; set; }
    
        public virtual tbCountry tbCountry { get; set; }
    }
}
