//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserLogonDetail
    {
        public string Username { get; set; }
        public string Version { get; set; }
        public string host { get; set; }
        public System.DateTime LogonTime { get; set; }
        public int IDX { get; set; }
        public string build { get; set; }
    }
}
