//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserRole
    {
        public int pkUserRoleID { get; set; }
        public int fkUserID { get; set; }
        public int fkRoleID { get; set; }
        public int fkDBRegionID { get; set; }
    
        public virtual tbRole tbRole { get; set; }
        public virtual tbDBRegionInfo tbDBRegionInfo { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
