//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWishIntegrationLeg
    {
        public int pkWishIntegrationLegID { get; set; }
        public int WishSectorID { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string WishFor { get; set; }
        public string WishEx { get; set; }
        public int fkReservationLegID { get; set; }
        public int fkWishIntegrationHdrID { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tbReservationLeg tbReservationLeg { get; set; }
        public virtual tbWISHIntegrationHeader tbWISHIntegrationHeader { get; set; }
    }
}
