//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWISHIntegrationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbWISHIntegrationHeader()
        {
            this.tbWishIntegrationLegs = new HashSet<tbWishIntegrationLeg>();
        }
    
        public int pkWishIntegrationHeaderID { get; set; }
        public int WISHBookingID { get; set; }
        public string WISHBookingStatus { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int WISHPGID { get; set; }
        public int WISHPGPax { get; set; }
        public string WISHPGName { get; set; }
        public string WishConsultant { get; set; }
        public int fkReservationHdrID { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tbReservationHeader tbReservationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbWishIntegrationLeg> tbWishIntegrationLegs { get; set; }
    }
}
