//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGP_ConnectInformation
    {
        public int IDX_Country { get; set; }
        public string GP_Server { get; set; }
        public string GP_Schedwin_Database { get; set; }
        public string GP_FunctionalCurrency { get; set; }
        public string GP_FunctionalCurrency_Desc { get; set; }
        public string GP_FunctionalCurrency_Symbol { get; set; }
        public string CURNCYID { get; set; }
        public string GP_Username { get; set; }
        public string GP_Password { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual tset_Countries tset_Countries { get; set; }
    }
}
