//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class timg_Documents
    {
        public int IDX { get; set; }
        public int IDX_Parent { get; set; }
        public string Name { get; set; }
        public int PAge { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Group { get; set; }
        public System.DateTime ExpDate { get; set; }
        public byte[] Document { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
