//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlst_Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tlst_Currency()
        {
            this.t_Techlog_Fuel = new HashSet<t_Techlog_Fuel>();
            this.tset_Airports = new HashSet<tset_Airports>();
            this.tset_Companies = new HashSet<tset_Companies>();
            this.tset_Countries = new HashSet<tset_Countries>();
        }
    
        public int IDX { get; set; }
        public string Currency { get; set; }
        public string CODE { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public string LOGUSERID { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Techlog_Fuel> t_Techlog_Fuel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_Airports> tset_Airports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_Companies> tset_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_Countries> tset_Countries { get; set; }
    }
}
