//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_WISHIntegrationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsch_WISHIntegrationHeader()
        {
            this.tsch_WishIntegrationLeg = new HashSet<tsch_WishIntegrationLeg>();
        }
    
        public int IDX { get; set; }
        public int WISHBookingID { get; set; }
        public string WISHBookingStatus { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int WISHPGID { get; set; }
        public int WISHPGPax { get; set; }
        public string WISHPGName { get; set; }
        public string WishConsultant { get; set; }
        public int IDX_RESHeader { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tsch_ReservationHeader tsch_ReservationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_WishIntegrationLeg> tsch_WishIntegrationLeg { get; set; }
    }
}
