//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_SplitReservations
    {
        public int IDX { get; set; }
        public Nullable<int> fkParentReservation { get; set; }
        public Nullable<int> fkChildReservation { get; set; }
    
        public virtual tsch_ReservationHeader tsch_ReservationHeader { get; set; }
        public virtual tsch_ReservationHeader tsch_ReservationHeader1 { get; set; }
    }
}
