//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_LegWeightBalances
    {
        public int IDX { get; set; }
        public int IDX_Leg { get; set; }
        public int IDX_Loading { get; set; }
        public string Row_Name { get; set; }
        public string Seating { get; set; }
        public double TotalWeight { get; set; }
        public bool Freight { get; set; }
        public bool CanEdit { get; set; }
        public bool UseForZFW { get; set; }
    }
}
