//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_Legs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsch_Legs()
        {
            this.tsch_LegsRes = new HashSet<tsch_LegsRes>();
        }
    
        public int IDX { get; set; }
        public int IDX_AC_Pilot { get; set; }
        public int FromAP { get; set; }
        public System.DateTime ETD { get; set; }
        public int ToAP { get; set; }
        public System.DateTime ETA { get; set; }
        public short NumPax { get; set; }
        public short DirectDistance { get; set; }
        public double Budget { get; set; }
        public double GameflightTime { get; set; }
        public string CoCode { get; set; }
        public Nullable<short> MaxTakeOffWeight { get; set; }
        public Nullable<short> MaxLandingWeight { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public Nullable<int> Turnaround { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual t_TechlogFlightTime t_TechlogFlightTime { get; set; }
        public virtual tset_Airports tset_Airports { get; set; }
        public virtual tset_Airports tset_Airports1 { get; set; }
        public virtual tsch_TrackingTime tsch_TrackingTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_LegsRes> tsch_LegsRes { get; set; }
        public virtual tsch_AC_Pilot tsch_AC_Pilot { get; set; }
    }
}
