//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_ReservationLegs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsch_ReservationLegs()
        {
            this.tsch_ReservationLegBudget = new HashSet<tsch_ReservationLegBudget>();
            this.tsch_LegsRes = new HashSet<tsch_LegsRes>();
            this.tsch_WishIntegrationLeg = new HashSet<tsch_WishIntegrationLeg>();
            this.tset_GPExportInfo = new HashSet<tset_GPExportInfo>();
        }
    
        public int IDX { get; set; }
        public int IDX_ResHeader { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int FromAp { get; set; }
        public string ExField { get; set; }
        public int ToAp { get; set; }
        public string ForField { get; set; }
        public Nullable<System.DateTime> EarliestEx { get; set; }
        public Nullable<System.DateTime> LatestEx { get; set; }
        public Nullable<System.DateTime> EarliestFor { get; set; }
        public Nullable<System.DateTime> LatestFor { get; set; }
        public double Budget { get; set; }
        public short DirectDistance { get; set; }
        public double GameflightTime { get; set; }
        public string Notes { get; set; }
        public int IDX_Personnel { get; set; }
        public int IDX_Company { get; set; }
        public Nullable<bool> TicketPrinted { get; set; }
        public Nullable<int> IDX_ScheduledFlight { get; set; }
        public Nullable<int> IDX_SpecificACType { get; set; }
        public Nullable<bool> SoleUse { get; set; }
        public Nullable<long> WISHIDLegs { get; set; }
        public Nullable<int> IDX_AreaPriceList { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string Voucher { get; set; }
        public string INV_Number { get; set; }
        public string RateType { get; set; }
        public Nullable<bool> FOC { get; set; }
        public string Currency { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public Nullable<int> IDX_LegParent { get; set; }
        public Nullable<int> SEQNo { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual tsch_ReservationHeader tsch_ReservationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_ReservationLegBudget> tsch_ReservationLegBudget { get; set; }
        public virtual tset_ACTypes tset_ACTypes { get; set; }
        public virtual tset_Airports tset_Airports { get; set; }
        public virtual tset_Airports tset_Airports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_LegsRes> tsch_LegsRes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_WishIntegrationLeg> tsch_WishIntegrationLeg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_GPExportInfo> tset_GPExportInfo { get; set; }
    }
}
