//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_WishIntegrationLeg
    {
        public int IDX { get; set; }
        public int WishSectorID { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string WishFor { get; set; }
        public string WishEx { get; set; }
        public int IDX_RESLeg { get; set; }
        public int IDX_WISH_Hdr { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
    
        public virtual tsch_ReservationLegs tsch_ReservationLegs { get; set; }
        public virtual tsch_WISHIntegrationHeader tsch_WISHIntegrationHeader { get; set; }
    }
}
