//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_WeightBalance
    {
        public int IDX { get; set; }
        public int IDX_Loadsheet { get; set; }
        public int IDX_Legs { get; set; }
        public int IDX_SectionType { get; set; }
        public string Section { get; set; }
        public string Type { get; set; }
        public int MaxPax { get; set; }
        public decimal MaxWeight { get; set; }
        public int AssignedPax { get; set; }
        public decimal AssignedWeight { get; set; }
        public Nullable<decimal> Arm { get; set; }
        public Nullable<decimal> Moment { get; set; }
    }
}
