//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsch_AC_Pilot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsch_AC_Pilot()
        {
            this.t_TechlogFlightTime = new HashSet<t_TechlogFlightTime>();
            this.tsch_Legs = new HashSet<tsch_Legs>();
            this.tsch_LegsRes = new HashSet<tsch_LegsRes>();
            this.tsch_Loadsheet = new HashSet<tsch_Loadsheet>();
        }
    
        public int IDX { get; set; }
        public System.DateTime FlightDate { get; set; }
        public int IDX_ACDetails { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IDX_Pilots { get; set; }
        public Nullable<int> IDX_Pilots2 { get; set; }
        public short RevisionNumber { get; set; }
        public bool Printed_This_Revision { get; set; }
        public int IDX_Airport_Aircraft { get; set; }
        public Nullable<int> IDX_Airport_Pilot { get; set; }
        public Nullable<int> IDX_Airport_Pilot2 { get; set; }
        public Nullable<int> IDX_Pilot2Type { get; set; }
        public string CoCode { get; set; }
        public Nullable<int> IDX_ACTypes { get; set; }
        public Nullable<int> TechLogID { get; set; }
        public Nullable<int> IDX_PT { get; set; }
        public Nullable<bool> SignedOff { get; set; }
        public Nullable<int> IDXUsername { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> ts_Date { get; set; }
        public int IDX_PilotType { get; set; }
        public string Notes { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_TechlogFlightTime> t_TechlogFlightTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_Legs> tsch_Legs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_LegsRes> tsch_LegsRes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_Loadsheet> tsch_Loadsheet { get; set; }
        public virtual tset_Personnel tset_Personnel { get; set; }
        public virtual tset_ACDetails tset_ACDetails { get; set; }
        public virtual tset_ACTypes tset_ACTypes { get; set; }
        public virtual tset_Airports tset_Airports { get; set; }
    }
}
