//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tset_ACDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tset_ACDetails()
        {
            this.t_Techlog = new HashSet<t_Techlog>();
            this.tset_ACDetailTypeStations = new HashSet<tset_ACDetailTypeStations>();
            this.tsch_AC_Pilot = new HashSet<tsch_AC_Pilot>();
        }
    
        public int IDX { get; set; }
        public int IDX_ACTypes { get; set; }
        public string Registration { get; set; }
        public double EmptyMass { get; set; }
        public double EmptyArm { get; set; }
        public Nullable<int> IDX_Owner { get; set; }
        public string Colours { get; set; }
        public string Equipment { get; set; }
        public float BuyingRate { get; set; }
        public float SellingRate { get; set; }
        public string InvoiceCode { get; set; }
        public string CoCode { get; set; }
        public int AvgSpeed { get; set; }
        public byte OwnAircraft { get; set; }
        public byte Active { get; set; }
        public Nullable<int> IDX_UnderWriter { get; set; }
        public string Liability { get; set; }
        public System.DateTime InsuranceExp { get; set; }
        public Nullable<int> Demurrage { get; set; }
        public Nullable<float> ShortCycleFee { get; set; }
        public Nullable<int> OLD_IDX { get; set; }
        public Nullable<int> OLD_IDX_ACTypes { get; set; }
        public Nullable<long> IDX_image1 { get; set; }
        public Nullable<long> IDX_image2 { get; set; }
        public Nullable<long> IDX_image3 { get; set; }
        public Nullable<long> IDX_image4 { get; set; }
        public Nullable<long> IDX_image5 { get; set; }
        public Nullable<long> IDX_image6 { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<System.DateTime> YOM { get; set; }
        public Nullable<double> TTA { get; set; }
        public Nullable<System.DateTime> DTT { get; set; }
        public Nullable<int> Reserve_Fuel { get; set; }
        public string NavComm1 { get; set; }
        public string NavComm2 { get; set; }
        public string AutoPilot { get; set; }
        public string Wx { get; set; }
        public string GPS { get; set; }
        public string TCAS { get; set; }
        public string EGPWS { get; set; }
        public string HF { get; set; }
        public string FM { get; set; }
        public string MFD { get; set; }
        public string Transponder { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }
        public int TotalFuelWT { get; set; }
        public string ProfitCenter { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATETIMESTAMP { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Techlog> t_Techlog { get; set; }
        public virtual tset_ACTypes tset_ACTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tset_ACDetailTypeStations> tset_ACDetailTypeStations { get; set; }
        public virtual tset_Companies tset_Companies { get; set; }
        public virtual tset_Companies tset_Companies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tsch_AC_Pilot> tsch_AC_Pilot { get; set; }
    }
}
