//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Tourplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string PCODE { get; set; }
        public string ANALYSIS_MASTER1 { get; set; }
        public string ANALYSIS_MASTER2 { get; set; }
        public string ANALYSIS_MASTER3 { get; set; }
        public System.DateTime CREATED { get; set; }
        public string TAXINDICATOR { get; set; }
        public decimal COMMISSION { get; set; }
        public decimal MARKUP { get; set; }
        public string LANGUAGE { get; set; }
        public string SUPPLIERCHAIN { get; set; }
        public string SUPPLIERMASTER { get; set; }
        public string DEFAULT_CURRENCY { get; set; }
        public string DELETED { get; set; }
        public int CRM_ID { get; set; }
        public int PREFER { get; set; }
        public string IMPORT_FORMAT { get; set; }
        public string IMPORT_FILE_LOCATION { get; set; }
        public string ADDRESS5 { get; set; }
        public string UDTEXT1 { get; set; }
        public string UDTEXT2 { get; set; }
        public string UDTEXT3 { get; set; }
        public string UDTEXT4 { get; set; }
        public string UDTEXT5 { get; set; }
        public string CREATED_BY { get; set; }
        public string EDITED_BY { get; set; }
        public System.DateTime EDITED_DATE { get; set; }
        public string INT_ACCESS { get; set; }
        public string INT_LOGIN { get; set; }
        public string INT_PASSWORD { get; set; }
        public string MAILING_NAME { get; set; }
        public string MAILING_ADDRESS1 { get; set; }
        public string MAILING_ADDRESS2 { get; set; }
        public string MAILING_ADDRESS3 { get; set; }
        public string MAILING_ADDRESS4 { get; set; }
        public string MAILING_ADDRESS5 { get; set; }
        public string MAILING_PCODE { get; set; }
        public int VOUCHER_UPDATE { get; set; }
        public int SOD_ID { get; set; }
        public string ANALYSIS_MASTER4 { get; set; }
        public string ANALYSIS_MASTER5 { get; set; }
        public string ANALYSIS_MASTER6 { get; set; }
    }
}
