//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Tourplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedwin_Vouchers
    {
        public Nullable<System.Guid> IDX { get; set; }
        public string CODE { get; set; }
        public string SERVICE { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime TRAVELDATE { get; set; }
        public string NAME { get; set; }
        public int Voucher { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Currency { get; set; }
        public string Reference { get; set; }
    }
}
