//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedwin.Tourplan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPRegionalEntities : DbContext
    {
        public TPRegionalEntities()
            : base("name=TPRegionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRM> CRMs { get; set; }
        public virtual DbSet<LOC> LOCs { get; set; }
        public virtual DbSet<Schedwin_Vouchers> Schedwin_Vouchers { get; set; }
    }
}
